# Generated by Django 6.0.3 on 2026-03-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_prospect_current_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='profile',
            new_name='position',
        ),
    ]
