# Generated by Django 6.0.3 on 2026-03-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_rename_profile_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(blank=True, db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitment.position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='prospect',
            field=models.ForeignKey(db_column='prospect_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.prospect'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requisition',
            field=models.ForeignKey(blank=True, db_column='requisition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitment.requisition'),
        ),
    ]
