from enum import Enum


class ErrorCode(Enum):

    NOT_FOUND = "NOT_FOUND"
    INVALID_STATE = "INVALID_STATE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
